---

dist: bionic

language: python
python:
  - 3.8
services: docker

env:
  global:
    - ROLE_NAME: apt-proxy
  matrix:
    - MOLECULE_DISTRO_BOX: generic/ubuntu1804

install:
  - sudo add-apt-repository universe && sudo apt update
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible*$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
- molecule test
