---

- name: configure apt proxy in {{ config_dir }}/{{ config_file }}
  template:
    src: apt-proxy-config
    dest: "{{ config_dir }}/{{ config_file }}"
    owner: root
    group: root
    mode: 0644

- name: configure proxy variables
  lineinfile:
    path: /etc/environment
    create: yes
    regexp: "^{{ item }}=.*$"
    line: "{{ item }}={{ proxy_url }}"
    state: present
  with_items:
    - http_proxy
    - https_proxy
    - HTTP_PROXY
    - HTTPS_PROXY

- name: configure no_proxy
  lineinfile:
    path: /etc/environment
    create: yes
    regexp: "^{{ item }}=.*$"
    line: "{{ item }}={{ no_proxy }}"
    state: present
  with_items:
    - no_proxy
    - NO_PROXY
  when: no_proxy is defined
