---
- name: Converge
  hosts: all
  roles:
    - role: apt-proxy
      http_proxy: http://proxy.server.local:8888
      https_proxy: http://proxy.server.local:8888
      no_proxy: 127.0.0.0,127.0.0.1,localhost
